window.PORTFOLIO_CONTENT = {
  "he": {
    "skip": "דילוג לתוכן",
    "navProjects": "פרויקטים",
    "navExperience": "ניסיון",
    "navAbout": "אודות",
    "navContact": "יצירת קשר",
    "heroEyebrow": "פיתוח. אבטחה. חשיבה אחרת.",
    "name": "טל ליבני<span class=\"accent\">.</span>",
    "heroDescription": "בונה מוצרים, מחבר מערכות והופך תהליכים מורכבים לפתרונות פשוטים. משלב פיתוח תוכנה עם ניסיון מעשי באבטחת מידע ואוטומציה.",
    "seeWork": "לפרויקטים שלי",
    "downloadResume": "הניסיון שלי",
    "location": "הרצליה, ישראל",
    "sayHello": "בואו נדבר",
    "scrollExplore": "עוד קצת עליי",
    "aboutEyebrow": "החיבור בין התחומים",
    "aboutTitle": "קוד טוב מתחיל<br>בהבנת התמונה המלאה.",
    "aboutText": "הדרך שלי עוברת בפיתוח מוצרי SaaS, תפעול מערכות אבטחה ובניית כלים פנימיים לארגונים. אני אוהב לקחת אחריות על הפתרון כולו: מהצורך הראשוני ועד למערכת שעובדת.",
    "aboutSecond": "לצד הרקע הטכנולוגי, השלמתי תואר ראשון במדעי המוח. הסקרנות להבין איך אנשים חושבים מלווה גם את הדרך שבה אני מתכנן תוכנה.",
    "aboutNote": "חשיבה אנליטית. סקרנות. אחריות מקצה לקצה.",
    "skillFront": "פיתוח ממשקים",
    "skillFrontText": "ממשקי משתמש ורכיבי מוצר ביישומי ווב.",
    "skillBack": "Backend ואוטומציה",
    "skillBackText": "API, עיבוד נתונים וכלים שמפשטים עבודה יומיומית.",
    "skillSecurity": "אבטחת מידע",
    "skillSecurityText": "תפעול אבטחה, תגובה לאירועים ושילוב מערכות הגנה.",
    "skillCloud": "ענן ותשתיות",
    "skillCloudText": "פריסה, מיקרו־שירותים ותהליכי פיתוח מתמשכים.",
    "projectsEyebrow": "פרויקט נבחר",
    "projectsTitle": "מרעיון למוצר.",
    "tzavAlt": "מסך ההתחברות לאפליקציית צו ראשון",
    "tzavCategory": "מוצר עצמאי · EdTech",
    "tzavTitle": "צו ראשון",
    "tzavText": "אפליקציה להכנה למבחנים פסיכוטכניים ולצו הראשון. תכנון, פיתוח ופריסה עצמאיים, עם ממשק React ושירותי Node.js ו-Firebase.",
    "tzavCaption": "צילום מסך מהאפליקציה: מסך הכניסה.",
    "tzavLink": "לאפליקציה",
    "experienceEyebrow": "הדרך המקצועית",
    "experienceTitle": "ניסיון שנבנה<br>בעולם האמיתי.",
    "experienceIntro": "מפיתוח מוצרים ועד הגנה על מערכות ארגוניות. בכל תחנה, שילוב של עשייה טכנית ואחריות.",
    "fullResume": "ליצירת קשר",
    "danelCompany": "Danel Group",
    "danelText": "פיתוח עצמאי של מערכות אוטומציה ואנליטיקה לצוותי IT ואבטחת מידע. כלים לנראות רשת, ביצועים, חולשות ועמידה בדרישות אבטחה, לצד תפעול מערכות EDR ו-Cisco.",
    "danelLocation": "רמת גן, ישראל",
    "independentCompany": "פיתוח עצמאי ולימודים",
    "independentText": "תכנון, פיתוח ופריסה של אפליקציית צו ראשון. פיתוח כלים אקדמיים ועבודה עם Python ולמידת מכונה בסיסית במקביל ללימודים.",
    "independentLocation": "תל אביב, ישראל",
    "totangoCompany": "Totango",
    "totangoText": "פיתוח בפלטפורמת SaaS: ממשקי React ו-Ember, שירותי Node.js ומיקרו־שירותים בסביבת AWS. עבודה בצוות Agile עם Docker ותהליכי CI/CD.",
    "totangoLocation": "תל אביב, ישראל",
    "cellcomCompany": "סלקום",
    "cellcomText": "תפעול מערכות אבטחת רשת ואפליקציות. פיתוח אוטומציות ב-Python וב-PowerShell ועבודה עם F5 ASM, Check Point, Forescout ו-FireGlass.",
    "cellcomLocation": "נתניה, ישראל",
    "navyCompany": "חיל הים · ממת״ם",
    "navyText": "ניטור ותגובה לאירועי אבטחה בסביבת SOC שפועלת 24/7, חקירת אירועים ופיתוח כלי אבטחה ב-C#, ב-Python וב-PowerShell.",
    "navyLocation": "רמת גן, ישראל",
    "educationEyebrow": "למידה וסקרנות",
    "educationTitle": "תשתית רחבה לחשיבה.",
    "eduTitle0": "תואר ראשון במדעי המוח",
    "eduInst0": "אוניברסיטת בר־אילן",
    "eduTitle1": "לימודי מדעי המחשב ומדעי המוח",
    "eduInst1": "אוניברסיטת בר־אילן",
    "eduTitle2": "Java / J2EE · מגן סייבר",
    "eduInst2": "ג׳ון ברייס · בסמ״ח",
    "contactEyebrow": "השלב הבא מתחיל בשיחה",
    "contactTitle": "יש לכם משהו<br>מעניין לבנות?",
    "contactText": "אשמח לשמוע על הזדמנויות בפיתוח תוכנה, אבטחת מידע ואוטומציה.",
    "backTop": "חזרה למעלה",
    "tzavDetailAlt": "תקריב של ממשק הכניסה לאפליקציית צו ראשון",
    "tzavDetailCategory": "צו ראשון · מבט מקרוב",
    "tzavDetailTitle": "חוויית הכניסה",
    "tzavDetailText": "ממשק כניסה בעברית, עם אפשרויות התחברות דרך Google ו-Facebook. מבט מקרוב על מסך הכניסה של האפליקציה שפיתחתי.",
    "tzavDetailCaption": "תקריב של אותו מסך כניסה מהאפליקציה.",
    "tzavDetailLink": "לאפליקציה"
  },
  "en": {
    "skip": "Skip to content",
    "navProjects": "Projects",
    "navExperience": "Experience",
    "navAbout": "About",
    "navContact": "Contact",
    "heroEyebrow": "DEVELOPMENT. SECURITY. A DIFFERENT PERSPECTIVE.",
    "name": "Tal Livny<span class=\"accent\">.</span>",
    "heroDescription": "I build products, connect systems and turn complex processes into straightforward solutions. Full-stack development, backed by hands-on security and automation experience.",
    "seeWork": "Explore my work",
    "downloadResume": "My experience",
    "location": "Herzliya, Israel",
    "sayHello": "Say hello",
    "scrollExplore": "Scroll to explore",
    "aboutEyebrow": "THE INTERSECTION",
    "aboutTitle": "Good software starts<br>with the bigger picture.",
    "aboutText": "My path spans SaaS products, security operations and internal tools for organizations. I like owning the whole solution, from the initial need to a working system.",
    "aboutSecond": "Alongside my technical background, I completed a B.Sc. in Neuroscience. A curiosity about how people think also shapes the way I approach software.",
    "aboutNote": "Analytical thinking. Curiosity. End-to-end ownership.",
    "skillFront": "Frontend development",
    "skillFrontText": "User interfaces and product components for the web.",
    "skillBack": "Backend & automation",
    "skillBackText": "APIs, data processing and tools that simplify daily work.",
    "skillSecurity": "Security operations",
    "skillSecurityText": "Security operations, incident response and defense platforms.",
    "skillCloud": "Cloud & infrastructure",
    "skillCloudText": "Deployment, microservices and continuous delivery.",
    "projectsEyebrow": "SELECTED PROJECT",
    "projectsTitle": "From idea to product.",
    "tzavAlt": "Tzav Rishon application sign-in screen",
    "tzavCategory": "INDEPENDENT PRODUCT · EDTECH",
    "tzavTitle": "Tzav Rishon",
    "tzavText": "A preparation app for psychometric tests and the first military assessment. Independently designed, developed and deployed with React, Node.js and Firebase.",
    "tzavCaption": "Screenshot from the application: sign-in screen.",
    "tzavLink": "Visit application",
    "experienceEyebrow": "THE JOURNEY",
    "experienceTitle": "Experience built<br>in the real world.",
    "experienceIntro": "From building products to protecting enterprise systems. Hands-on work and responsibility at every step.",
    "fullResume": "Get in touch",
    "danelCompany": "Danel Group",
    "danelText": "Independently built automation and analytics systems for IT and InfoSec teams: network visibility, performance, vulnerabilities and security compliance. Operated EDR and Cisco security platforms.",
    "danelLocation": "Ramat Gan, Israel",
    "independentCompany": "Independent development & studies",
    "independentText": "Designed, developed and deployed Tzav Rishon. Built academic tools with Python and explored basic machine learning alongside my studies.",
    "independentLocation": "Tel Aviv, Israel",
    "totangoCompany": "Totango",
    "totangoText": "Built SaaS features with React, Ember, Node.js and AWS microservices. Worked in an Agile team with Docker and CI/CD workflows.",
    "totangoLocation": "Tel Aviv, Israel",
    "cellcomCompany": "Cellcom",
    "cellcomText": "Operated network and application security systems. Built Python and PowerShell automations and worked with F5 ASM, Check Point, Forescout and FireGlass.",
    "cellcomLocation": "Netanya, Israel",
    "navyCompany": "Israeli Navy · Mamtam",
    "navyText": "Monitoring, incident response and forensics in a 24/7 SOC. Developed security tools with C#, Python and PowerShell.",
    "navyLocation": "Ramat Gan, Israel",
    "educationEyebrow": "LEARNING & CURIOSITY",
    "educationTitle": "A broader foundation.",
    "eduTitle0": "B.Sc. in Neuroscience",
    "eduInst0": "Bar-Ilan University",
    "eduTitle1": "Computer Science & Neuroscience studies",
    "eduInst1": "Bar-Ilan University",
    "eduTitle2": "Java / J2EE · Cyber Defender",
    "eduInst2": "John Bryce · Basmach",
    "contactEyebrow": "THE NEXT STEP STARTS WITH A CONVERSATION",
    "contactTitle": "Something interesting<br>to build?",
    "contactText": "Let’s talk about software development, security and automation opportunities.",
    "backTop": "Back to top",
    "tzavDetailAlt": "Close-up of the Tzav Rishon sign-in interface",
    "tzavDetailCategory": "TZAV RISHON · A CLOSER LOOK",
    "tzavDetailTitle": "The sign-in experience",
    "tzavDetailText": "A Hebrew sign-in interface with Google and Facebook authentication options. A closer look at the entry screen of the application I developed.",
    "tzavDetailCaption": "A closer view of the same application sign-in screen.",
    "tzavDetailLink": "Visit application"
  }
};

